-- Migrates the original RentaYa development schema to CONTRATO_BACKEND_API.md.
-- Run once against an existing database. The script preserves users and domain data.

BEGIN;

ALTER TABLE propiedad ADD COLUMN IF NOT EXISTS area integer;
ALTER TABLE propiedad ADD COLUMN IF NOT EXISTS creado_en date NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE visita ADD COLUMN IF NOT EXISTS creado_en timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS conversacion (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  propiedad_id integer NOT NULL,
  propietario_id integer NOT NULL,
  inquilino_id integer NOT NULL,
  ultimo_mensaje varchar(500) NOT NULL DEFAULT '',
  ultimo_mensaje_en timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  creado_en timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_conversacion_propiedad FOREIGN KEY (propiedad_id) REFERENCES propiedad (id),
  CONSTRAINT fk_conversacion_propietario FOREIGN KEY (propietario_id) REFERENCES usuario (id),
  CONSTRAINT fk_conversacion_inquilino FOREIGN KEY (inquilino_id) REFERENCES usuario (id),
  CONSTRAINT uq_conversacion_propiedad_participantes UNIQUE (propiedad_id, propietario_id, inquilino_id)
);

ALTER TABLE mensaje ADD COLUMN IF NOT EXISTS conversacion_id integer;

-- The original message model linked a property, sender and receiver directly.
-- Convert those rows into one conversation per property/owner/tenant tuple.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'mensaje'
      AND column_name = 'propiedad_id'
  ) THEN
    EXECUTE $migration$
      INSERT INTO conversacion (
        propiedad_id,
        propietario_id,
        inquilino_id,
        ultimo_mensaje,
        ultimo_mensaje_en,
        creado_en
      )
      SELECT DISTINCT
        m.propiedad_id,
        p.propietario_id,
        CASE
          WHEN m.emisor_id = p.propietario_id THEN m.receptor_id
          ELSE m.emisor_id
        END,
        '',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
      FROM mensaje m
      JOIN propiedad p ON p.id = m.propiedad_id
      WHERE p.propietario_id IN (m.emisor_id, m.receptor_id)
      ON CONFLICT (propiedad_id, propietario_id, inquilino_id) DO NOTHING
    $migration$;

    EXECUTE $migration$
      UPDATE mensaje m
      SET conversacion_id = c.id
      FROM propiedad p
      JOIN conversacion c ON c.propiedad_id = p.id
        AND c.propietario_id = p.propietario_id
      WHERE p.id = m.propiedad_id
        AND c.inquilino_id = CASE
          WHEN m.emisor_id = p.propietario_id THEN m.receptor_id
          ELSE m.emisor_id
        END
    $migration$;

    IF EXISTS (SELECT 1 FROM mensaje WHERE conversacion_id IS NULL) THEN
      RAISE EXCEPTION 'No se pudieron asociar todos los mensajes anteriores a una conversación';
    END IF;

    ALTER TABLE mensaje DROP COLUMN propiedad_id;
    ALTER TABLE mensaje DROP COLUMN receptor_id;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'mensaje'
      AND column_name = 'fecha_envio'
      AND data_type = 'timestamp without time zone'
  ) THEN
    ALTER TABLE mensaje
      ALTER COLUMN fecha_envio TYPE timestamp with time zone
      USING fecha_envio AT TIME ZONE 'UTC';
  END IF;
END $$;

ALTER TABLE mensaje ALTER COLUMN contenido TYPE varchar(500);
ALTER TABLE mensaje ALTER COLUMN conversacion_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_mensaje_conversacion') THEN
    ALTER TABLE mensaje
      ADD CONSTRAINT fk_mensaje_conversacion
      FOREIGN KEY (conversacion_id) REFERENCES conversacion (id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_usuario_rol') THEN
    ALTER TABLE usuario
      ADD CONSTRAINT ck_usuario_rol CHECK (rol IN ('PROPIETARIO', 'INQUILINO')) NOT VALID;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_propiedad_precio') THEN
    ALTER TABLE propiedad
      ADD CONSTRAINT ck_propiedad_precio CHECK (precio > 0) NOT VALID;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_propiedad_habitaciones') THEN
    ALTER TABLE propiedad
      ADD CONSTRAINT ck_propiedad_habitaciones CHECK (habitaciones >= 1) NOT VALID;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_propiedad_banos') THEN
    ALTER TABLE propiedad
      ADD CONSTRAINT ck_propiedad_banos CHECK (banos >= 1) NOT VALID;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_propiedad_area') THEN
    ALTER TABLE propiedad
      ADD CONSTRAINT ck_propiedad_area CHECK (area IS NULL OR area > 0) NOT VALID;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_propiedad_estado') THEN
    ALTER TABLE propiedad
      ADD CONSTRAINT ck_propiedad_estado CHECK (estado IN ('Disponible', 'Inactivo')) NOT VALID;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_visita_estado') THEN
    ALTER TABLE visita
      ADD CONSTRAINT ck_visita_estado CHECK (estado IN ('Pendiente', 'Aceptada', 'Rechazada')) NOT VALID;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_mensaje_contenido') THEN
    ALTER TABLE mensaje
      ADD CONSTRAINT ck_mensaje_contenido
      CHECK (length(trim(contenido)) BETWEEN 1 AND 500) NOT VALID;
  END IF;
END $$;

WITH ultimo AS (
  SELECT DISTINCT ON (conversacion_id)
    conversacion_id,
    contenido,
    fecha_envio
  FROM mensaje
  ORDER BY conversacion_id, fecha_envio DESC
)
UPDATE conversacion c
SET ultimo_mensaje = u.contenido,
    ultimo_mensaje_en = u.fecha_envio
FROM ultimo u
WHERE c.id = u.conversacion_id;

CREATE UNIQUE INDEX IF NOT EXISTS uq_usuario_correo_normalizado ON usuario (lower(correo));
CREATE INDEX IF NOT EXISTS idx_propiedad_busqueda ON propiedad (estado, distrito, precio);
CREATE INDEX IF NOT EXISTS idx_propiedad_propietario ON propiedad (propietario_id, creado_en DESC);
CREATE INDEX IF NOT EXISTS idx_foto_propiedad ON foto (propiedad_id);
CREATE INDEX IF NOT EXISTS idx_visita_propiedad_estado ON visita (propiedad_id, estado);
CREATE INDEX IF NOT EXISTS idx_visita_inquilino ON visita (inquilino_id, creado_en DESC);
CREATE INDEX IF NOT EXISTS idx_visita_propietario ON visita (propiedad_id, creado_en DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_visita_pendiente
  ON visita (propiedad_id, inquilino_id)
  WHERE estado = 'Pendiente';
CREATE INDEX IF NOT EXISTS idx_conversacion_propietario
  ON conversacion (propietario_id, ultimo_mensaje_en DESC);
CREATE INDEX IF NOT EXISTS idx_conversacion_inquilino
  ON conversacion (inquilino_id, ultimo_mensaje_en DESC);
CREATE INDEX IF NOT EXISTS idx_mensaje_conversacion ON mensaje (conversacion_id, fecha_envio);
CREATE UNIQUE INDEX IF NOT EXISTS uq_favorito_usuario_propiedad_idx
  ON favorito (usuario_id, propiedad_id);
CREATE INDEX IF NOT EXISTS idx_favorito_usuario ON favorito (usuario_id);
CREATE INDEX IF NOT EXISTS idx_favorito_propiedad ON favorito (propiedad_id);

COMMIT;
