-- RentaYa schema for PostgreSQL 17.
-- Reference schema for a fresh database. Spring/Hibernate also creates these structures.

CREATE TABLE usuario (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(50) NOT NULL,
  apellido varchar(50) NOT NULL,
  correo varchar(100) NOT NULL UNIQUE,
  contrasena varchar(255) NOT NULL,
  telefono varchar(15) NOT NULL,
  rol varchar(20) NOT NULL,
  CONSTRAINT ck_usuario_rol CHECK (rol IN ('PROPIETARIO', 'INQUILINO'))
);

CREATE TABLE propiedad (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  propietario_id integer NOT NULL,
  titulo varchar(100) NOT NULL,
  distrito varchar(50) NOT NULL,
  direccion varchar(150) NOT NULL,
  precio decimal(8,2) NOT NULL,
  habitaciones integer NOT NULL,
  banos integer NOT NULL,
  area integer,
  descripcion text NOT NULL,
  estado varchar(20) NOT NULL DEFAULT 'Disponible',
  creado_en date NOT NULL DEFAULT CURRENT_DATE,
  CONSTRAINT fk_propiedad_propietario FOREIGN KEY (propietario_id) REFERENCES usuario (id),
  CONSTRAINT ck_propiedad_precio CHECK (precio > 0),
  CONSTRAINT ck_propiedad_habitaciones CHECK (habitaciones >= 1),
  CONSTRAINT ck_propiedad_banos CHECK (banos >= 1),
  CONSTRAINT ck_propiedad_area CHECK (area IS NULL OR area > 0),
  CONSTRAINT ck_propiedad_estado CHECK (estado IN ('Disponible', 'Inactivo'))
);

CREATE TABLE foto (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  propiedad_id integer NOT NULL,
  url varchar(255) NOT NULL,
  CONSTRAINT fk_foto_propiedad FOREIGN KEY (propiedad_id) REFERENCES propiedad (id) ON DELETE CASCADE
);

CREATE TABLE visita (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  propiedad_id integer NOT NULL,
  inquilino_id integer NOT NULL,
  fecha date NOT NULL,
  hora time NOT NULL,
  estado varchar(20) NOT NULL DEFAULT 'Pendiente',
  creado_en timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_visita_propiedad FOREIGN KEY (propiedad_id) REFERENCES propiedad (id),
  CONSTRAINT fk_visita_inquilino FOREIGN KEY (inquilino_id) REFERENCES usuario (id),
  CONSTRAINT ck_visita_estado CHECK (estado IN ('Pendiente', 'Aceptada', 'Rechazada'))
);

CREATE TABLE conversacion (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  propiedad_id integer NOT NULL,
  propietario_id integer NOT NULL,
  inquilino_id integer NOT NULL,
  ultimo_mensaje varchar(500) NOT NULL DEFAULT '',
  ultimo_mensaje_en timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  creado_en timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_conversacion_propiedad FOREIGN KEY (propiedad_id) REFERENCES propiedad (id),
  CONSTRAINT fk_conversacion_propietario FOREIGN KEY (propietario_id) REFERENCES usuario (id),
  CONSTRAINT fk_conversacion_inquilino FOREIGN KEY (inquilino_id) REFERENCES usuario (id),
  CONSTRAINT uq_conversacion_propiedad_participantes UNIQUE (propiedad_id, propietario_id, inquilino_id)
);

CREATE TABLE mensaje (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversacion_id integer NOT NULL,
  emisor_id integer NOT NULL,
  contenido varchar(500) NOT NULL,
  fecha_envio timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_mensaje_conversacion FOREIGN KEY (conversacion_id) REFERENCES conversacion (id) ON DELETE CASCADE,
  CONSTRAINT fk_mensaje_emisor FOREIGN KEY (emisor_id) REFERENCES usuario (id),
  CONSTRAINT ck_mensaje_contenido CHECK (length(trim(contenido)) BETWEEN 1 AND 500)
);

CREATE TABLE favorito (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id integer NOT NULL,
  propiedad_id integer NOT NULL,
  CONSTRAINT fk_favorito_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE,
  CONSTRAINT fk_favorito_propiedad FOREIGN KEY (propiedad_id) REFERENCES propiedad (id) ON DELETE CASCADE,
  CONSTRAINT uq_favorito_usuario_propiedad UNIQUE (usuario_id, propiedad_id)
);

CREATE INDEX idx_propiedad_busqueda ON propiedad (estado, distrito, precio);
CREATE UNIQUE INDEX uq_usuario_correo_normalizado ON usuario (lower(correo));
CREATE INDEX idx_propiedad_propietario ON propiedad (propietario_id, creado_en DESC);
CREATE INDEX idx_foto_propiedad ON foto (propiedad_id);
CREATE INDEX idx_visita_propiedad_estado ON visita (propiedad_id, estado);
CREATE INDEX idx_visita_inquilino ON visita (inquilino_id, creado_en DESC);
CREATE INDEX idx_visita_propietario ON visita (propiedad_id, creado_en DESC);
CREATE UNIQUE INDEX uq_visita_pendiente
  ON visita (propiedad_id, inquilino_id)
  WHERE estado = 'Pendiente';
CREATE INDEX idx_conversacion_propietario ON conversacion (propietario_id, ultimo_mensaje_en DESC);
CREATE INDEX idx_conversacion_inquilino ON conversacion (inquilino_id, ultimo_mensaje_en DESC);
CREATE INDEX idx_mensaje_conversacion ON mensaje (conversacion_id, fecha_envio);
CREATE INDEX idx_favorito_usuario ON favorito (usuario_id);
CREATE INDEX idx_favorito_propiedad ON favorito (propiedad_id);
