-- RentaYa schema (Read-only)
CREATE TABLE "usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) NOT NULL,
  "apellido" varchar(50) NOT NULL,
  "correo" varchar(100) UNIQUE NOT NULL,
  "contrasena" varchar(255) NOT NULL,
  "telefono" varchar(15) NOT NULL,
  "rol" varchar(20) NOT NULL
);

CREATE TABLE "propiedad" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "propietario_id" int NOT NULL,
  "titulo" varchar(100) NOT NULL,
  "distrito" varchar(50) NOT NULL,
  "direccion" varchar(150) NOT NULL,
  "precio" decimal(8,2) NOT NULL,
  "habitaciones" int NOT NULL,
  "banos" int NOT NULL,
  "descripcion" text NOT NULL,
  "estado" varchar(20) NOT NULL DEFAULT 'Disponible'
);

CREATE TABLE "foto" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "propiedad_id" int NOT NULL,
  "url" varchar(255) NOT NULL
);

CREATE TABLE "visita" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "propiedad_id" int NOT NULL,
  "inquilino_id" int NOT NULL,
  "fecha" date NOT NULL,
  "hora" time NOT NULL,
  "estado" varchar(20) NOT NULL DEFAULT 'Pendiente'
);

CREATE TABLE "mensaje" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "propiedad_id" int NOT NULL,
  "emisor_id" int NOT NULL,
  "receptor_id" int NOT NULL,
  "contenido" varchar(500) NOT NULL,
  "fecha_envio" datetime NOT NULL
);

CREATE TABLE "favorito" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int NOT NULL,
  "propiedad_id" int NOT NULL
);

ALTER TABLE "propiedad" ADD FOREIGN KEY ("propietario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "foto" ADD FOREIGN KEY ("propiedad_id") REFERENCES "propiedad" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "visita" ADD FOREIGN KEY ("propiedad_id") REFERENCES "propiedad" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "visita" ADD FOREIGN KEY ("inquilino_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mensaje" ADD FOREIGN KEY ("propiedad_id") REFERENCES "propiedad" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mensaje" ADD FOREIGN KEY ("emisor_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mensaje" ADD FOREIGN KEY ("receptor_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "favorito" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "favorito" ADD FOREIGN KEY ("propiedad_id") REFERENCES "propiedad" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- Búsqueda y filtrado de propiedades (HU04)
CREATE INDEX IF NOT EXISTS idx_propiedad_busqueda
    ON propiedad (estado, distrito, precio);

-- Propiedades de un propietario (HU07, HU10)
CREATE INDEX IF NOT EXISTS idx_propiedad_propietario
    ON propiedad (propietario_id);

-- Fotos de una propiedad (HU05)
CREATE INDEX IF NOT EXISTS idx_foto_propiedad
    ON foto (propiedad_id);

-- Visitas por propiedad y estado (HU06, HU07)
CREATE INDEX IF NOT EXISTS idx_visita_propiedad_estado
    ON visita (propiedad_id, estado);

-- Visitas solicitadas por un inquilino
CREATE INDEX IF NOT EXISTS idx_visita_inquilino
    ON visita (inquilino_id);

-- Conversación de mensajes por propiedad y participantes (HU08)
CREATE INDEX IF NOT EXISTS idx_mensaje_conversacion
    ON mensaje (propiedad_id, emisor_id, receptor_id);

-- Favoritos por usuario (HU09)
CREATE INDEX IF NOT EXISTS idx_favorito_usuario
    ON favorito (usuario_id);

-- Favoritos por propiedad
CREATE INDEX IF NOT EXISTS idx_favorito_propiedad
    ON favorito (propiedad_id);

-- Regla de negocio: un usuario no puede marcar la misma propiedad como favorita más de una vez
ALTER TABLE favorito
    ADD CONSTRAINT uq_favorito_usuario_propiedad UNIQUE (usuario_id, propiedad_id);
